marinatedconcrete/config

.github/workflows/usb-image.yml, Earthfile, images/Earthfile, images/usb-image/Earthfile
This adds a new images directory, and moves the usb-image build into its own `Earthfile`.  This will give us more structure to add additional images over time.
=> Refactor images to allow for more images with organization

.github/workflows/kairos-ubuntu-22-lts.yml, images/Earthfile, images/kairos-ubuntu-22-lts/Earthfile, renovate.json
Right now, this just adds `vim`, but we can do much more with it over time!  This also supports amd64 and Raspberry Pi systems that support arm64.
=> Add a custom Kairos image

Earthfile, kustomization/components/operator-lifecycle-manager/README.md, kustomization/components/operator-lifecycle-manager/kustomization.yml
This adds OLM, as well as kustomization validation since it's the first component.
=> Add Operator Lifecycle Manager

Earthfile, ansible/galaxy.yml, renovate.json
I solved the hard part (hidden files) but not the easy part. Oops.
This PR also applies the lint changes that should have been caught earlier.
=> Ensure that prettier lints all files in the repo

.github/workflows/publish-devcontainer-features.yml, .github/workflows/validate-devcontainer-features.yml, devcontainer/features/ansible/README.md, devcontainer/features/ansible/devcontainer-feature.json, devcontainer/features/ansible/install.sh
I did not figure out how to get it to push the feature on PR, so there may be some trial & error here.
=> Generate a feature to install ansible and run a playbook

.devcontainer/devcontainer.json, Earthfile
Fixes #46 
You can run `earthly +lint --write=true` to have it autoformat for you. This will let us migrate to faster tools in the future.
=> Add option to write corrected prettier output back to repo

kustomization/components/mosquitto/README.md, kustomization/components/mosquitto/configmap/default-config/mosquitto.conf, kustomization/components/mosquitto/configmap/scripts/create_password.conf.sh, kustomization/components/mosquitto/deployment.yml, kustomization/components/mosquitto/kustomization.yml, kustomization/components/mosquitto/persistentvolumeclaim.yml, kustomization/components/mosquitto/service.yml
=> Add Mosquitto Kustomize Component

.devcontainer/devcontainer.json
This mounts the `.earthly` directory from the user's homedir so that any configuration (like login or org) persists between devcontainer instances.
=> Support preserving Earthly configuration

.github/workflows/kairos-ubuntu-22-lts.yml, .github/workflows/kairos-zsh-bundle.yml, .github/workflows/kustomization-tests.yml, .github/workflows/usb-image.yml, earthly.sh
This reverts commit 078a52289efc9708e4eba55fedb23782d584b7f1. We suspect this is causing CI failures.
=> Revert "Update earthly/earthly Docker tag to v0.7.23 (#90)"

kustomization/components/kube-vip/README.md, kustomization/components/kube-vip/daemonset.yml, kustomization/components/kube-vip/kustomization.yml, kustomization/components/kube-vip/namespace.yml, kustomization/components/kube-vip/rbac.yml, kustomization/tests/kube-vip/kustomization.yml, kustomization/tests/kube-vip/namespace.yml
This is ready to use in both clusters
=> Upstream kube-vip from sdwilsh

.github/workflows/universal-silabs-flasher.yml, images/Earthfile, images/universal-silabs-flasher/Earthfile, images/universal-silabs-flasher/requirements.txt
This should be helpful for flashing SkyConnect modems, per https://github.com/NabuCasa/universal-silabs-flasher
=> Add image for the silabs firmware flasher

.github/workflows/kustomization-tests.yml
Should ensure that PRs like #86 don't break these tests
=> Add more ansible files to the kustomize test paths

kustomization/components/paperless/README.md, kustomization/components/paperless/kustomization.yml, kustomization/components/paperless/pvc.yml, kustomization/components/paperless/service.yml, kustomization/components/paperless/statefulset.yml, kustomization/components/redis/README.md, kustomization/components/redis/deployment.yml, kustomization/components/redis/kustomization.yml, kustomization/components/redis/pvc.yml, kustomization/components/redis/service.yml, kustomization/components/samba-upload/README.md, kustomization/components/samba-upload/deployment.yml, kustomization/components/samba-upload/kustomization.yml, kustomization/components/samba-upload/service.yml, kustomization/tests/paperless/kustomization.yml, kustomization/tests/paperless/namespace.yml, kustomization/tests/paperless/secret.yml
This is a start for sharing paperless between repos. Closes #58.
=> Upstream paperless components

images/kairos-ubuntu-22-lts/Earthfile
Things changed since 2.4.1. I've not done this development myself, so I split the arm/x86 builds so that I can at least get the amd64 ones right. Hopefully the arm64 ones work in CI.
- Split the amd/arm images since the latter needs emulator support
- Fix k3s release name
- Upgrade to 2.5.0
=> Update kairos builds

images/kairos-ubuntu-22-lts/Earthfile
This is something we can easily diff against in our upgrade script to know when there's an upgrade. I left the Kairos variables alone because a) they reflect what Kairos version this is built off of, and b) they might affect other parts of the system that we're not aware of. This seems consistent with the [Customizing the system image section of the Kairos docs](https://kairos.io/docs/advanced/customizing/) which shows adding a new variable to this file to reflect the customized version.
=> Put the image metadata into the OS release

renovate.json
I have a similar rule for my repo and this helps keep the PR noise down. All the checks will continue to run I believe, and the 3 day waiting period helps de-risk including bugs that are quickly discovered by the community. We could go longer than 3 days.
=> Enable renovate to automerge all patch level updates

kustomization/components/unifi-network-application/README.md, kustomization/components/unifi-network-application/configmap/generate-init-mongo.sh, kustomization/components/unifi-network-application/configmap/shutdown-mongo.js, kustomization/components/unifi-network-application/kustomization.yml, kustomization/components/unifi-network-application/serverstransport.yml, kustomization/components/unifi-network-application/service.yml, kustomization/components/unifi-network-application/statefulset.yml, kustomization/tests/unifi-network-application/kustomization.yml, kustomization/tests/unifi-network-application/namespace.yml
=>  Add a new Unifi Network Application Component 

ansible/Earthfile, images/universal-silabs-flasher/Earthfile
It's been out for about a year. Bullseye is about 3 years old and is hitting a support milestone soon.
https://en.wikipedia.org/wiki/Debian_version_history
=> Upgrade debian to bookworm

ansible/roles/minikube_test/defaults/main.yml, ansible/roles/minikube_test/tasks/main.yml, justfile, kustomization/components/unifi-network-application/kustomization.yml, kustomization/tests/kube-vip/test.yml, kustomization/tests/mosquitto/test.yml, kustomization/tests/paperless/test.yml, kustomization/tests/priorityclass/test.yml, kustomization/tests/unifi-network-application/kustomization.yml, kustomization/tests/unifi-network-application/secret.yml, kustomization/tests/unifi-network-application/test.yml
This does a few things (broken out into different commits):
- pin all containers used by the component
- adds the ability for each component to define custom tests
- adds the ability to have local storage provisioning in tests
- asserts that the unifi stateful set comes up
- asserts that the unifi service has endpoints that are subsets
=> Greatly improve testing of the unifi-network-application component

.release-please-manifest.json, release-please-config.json, renovate/README.md, renovate/default.json
We can use this in each of our repositories.  To start, it adds support for our package versioning and where to look for it in our repositories. This assumes a layout that is suggested by kustomize:
- `kustomization`
- `bases`
- `components`
- `overlays`
Closes #249
=> feat: Create a new shareable Renovate config

.devcontainer/devcontainer.json, renovate.json
This fixes #269.
The original commit, 3143f97673cb8c899405c79c5fc6d2be279bd158, did not properly setup the renovate file to parse these.  Since we now have a shared config that can do that for us (pending release of 2.0.0 in #270), this change undoes the work in the original commit and instead depends on our shared config to pick it up.
Validated with these two tests of our updated config:
* https://regex101.com/r/SE5Vfw/1
* https://regex101.com/r/ocT8Ie/1
=> fix: track versioned components in devcontainer spec

renovate.json
These two are semi-annoying. The gh-cli ones should be dealt with more frequently than the renovate ones, because the apt-repo only stores the latest version. The devcontainer seems to install from source but I'm not sure we want to rely on that.
=> Auto-update frequently updating packages

renovate/devcontainer.json
This doesn't seem to work in practice (or at least we never figured out the right syntax).
=> fix: remove renovate deb matching

kustomization/components/kube-vip/rbac.yml
Their suggested settings have changed, and we were missing some of it: https://kube-vip.io/manifests/rbac.yaml
Sadly, this isn't versioned in their repository anywhere, so we can't pin it to a version.
=> fix: update RBAC for kube-vip

.devcontainer/devcontainer.json
We cannot get renovate to upgrade these properly, so `latest` is likely good enough.  It seems like something is broken with the pinned versions we have in here on my laptop as it is (I cannot run minikube anymore in the devcontainer).
=> fix: stop badly pinning docker-in-docker versions

.devcontainer/post-create-command.sh
As noted in https://github.com/devcontainers/features/issues/1235, the docker-in-docker feature simply always forces the use of `iptables-legacy`.  This doesn't work in newer fedora kernels, and so this just does a quick `uname` check to verify that we have it, and swaps to `iptables-nftables` if it matches.
=> fix: workaround docker-in-docker issue on newer fedora kernel

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, justfile, kustomization/components/kube-vip/README.md, kustomization/components/kube-vip/daemonset.yml, kustomization/tests/kube-vip/kustomization.yml, renovate.json
This is a breaking change because it potentially breaks patching, as the namespace may have to be added to patch files as seen in the test updates in this change.
This uses kube-vip's manifest generation utility, which their docs really push you to use.  This is versioned with the kube-vip release in our repository, which is synced with renovate.
This change also documents the required and optional patches for kube-vip.
Tested renovate config settings with https://regex101.com/r/FwnumZ/1
=> !feat: generate kube-vip manifest

kustomization/components/factorio/statefulset.yml, kustomization/components/unifi-network-application/statefulset.yml
I recently moved to using server side apply for all of my argocd applications, and now many things are showing up as out of sync.  It looks like we've always been using a shorthand for PVCs that becomes more apparent once you use server side apply.
This changes fixes that by setting the `apiVersion` and `kind` for each `volumeClaimTemplate` in our `StatefulSet`s.
=> fix: handle syntax change for volume claim templates

renovate.json
From the docs:
> The `regex` manager matches are done per-file, not per-line! This
> means the `^` and `$` regex assertions only match the beginning
> and end of the entire file.
This fixes our two broken matchers.
=> fix: renovate does not handle `^` and `$` in `matchStrings`

.gitignore
This looks like a working directory for collections and roles, among other things.  We should ignore this.
=> fix: running `just lint` creates `ansible/.ansible`

justfile, kustomization/components/kube-vip/README.md, kustomization/components/kube-vip/daemonset.yml, kustomization/tests/kube-vip/kustomization.yml
This updates codegen to use a `fieldRef` instead of requiring a patch if one changes the deployed namespace.
This is also safer, because it's easy to forget to update this, and then find that kube-vip isn't working correctly.
=> fix: make it easier to override the namespace

.devcontainer/devcontainer.json
There's more to do on the Fedora system itself to get the permissions right for podman.
=> Fix devcontainer for Fedora

.github/workflows/image-kairos-ubuntu.yml
I think this line was in error and while I could refine it to only look at certain releases, I think @sdwilsh intended for this trigger to be removed.
=> Don't try to build kairos-ubuntu image on every release

renovate.json
Had to run the renovate CLI with `LOG_LEVEL=debug renovate --dry-run=full --platform=local 2>&1 | less` to get it to spit out what the package name is. I once again inferred incorrectly from the PR.
If correct, this should unblock the pending Node JS upgrade PR (#347) to automerge.
=> Fix nodejs package name in automerge rule

images/vscode-ssh-server/README.md
Touching the readme should be sufficient, along with a commit that has the semantic commit message
=> feat: Get the vscode-ssh-package to build

.github/workflows/image-vscode-ssh-server.yml
The tags are generated using the `-` instead of `@` and there's no `v` prefix. Maybe we try this before #371? I did a quick check for new issues for it and I don't see anything.
=> fix: Fix tag trigger for vscode-ssh-server

justfile, kustomization/components/kube-vip/README.md, kustomization/components/kube-vip/daemonset/services.yml, kustomization/components/kube-vip/daemonset/vip.yml, kustomization/components/kube-vip/kustomization.yml
By default, kube-vip will route all traffic for services through the control plane.  This allows it to pick non-control planes in which to listen for service traffic (which it elects one node per service that needs an IP).
=> feat!: split kube-vip service and control plane VIP DaemonSets

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
- drop devcontainer shellcheck feature (failing CI due to broken dependency)
- install shellcheck directly in the devcontainer Dockerfile
=> chore: Install shellcheck via Dockerfile

.devcontainer/devcontainer.json, renovate.json
I do not know if we had the `extractVersion` feature available before but it seems to simplify the setup here.
=> Switch Kustomize to use github releases

renovate/marinatedconcrete.json
Renovate groups all the updates from this repository into a single Pull Request.  Ultimately, that's because they all share the same branch name.  We can override that by either changing the branch name (which can break other packages, so it is a bad idea), or by specifying a group for each package.
This solution is verbose, but it works great.  I was able to pull out a Unifi update in https://github.com/sdwilsh/ansible-playbooks/pull/1191, as an example.
=> feat: Ensure each thing we release is not grouped by renovate

renovate/recommended.json
The actual version update is easy to read from the commit contents, so the table was not very useful. This does bloat the commit message quite a bit but it gives a good historical record. And maybe some day something will format this markdown nicely.
=> Include the release notes in the body commit

images/kairos-ubuntu/Dockerfile, images/kairos-ubuntu/build_files/customization.sh
This is needed for the [`ansible.builtin.expect`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/expect_module.html) module to work, which I am working on a play for to have our encrypted longhorn volumes be trim-able.
=> feat: include python3-pexpect in our kairos image

release-please-config.json
This is only used for the devcontainer, and is not actually released. It should greatly cut down on spam for releases of this code.
=> fix: exclude ansible/requirements.txt

ansible/roles/longhorn_allow_encrypted_trim/README.md, ansible/roles/longhorn_allow_encrypted_trim/meta/main.yml, ansible/roles/longhorn_allow_encrypted_trim/tasks/main.yml, ansible/roles/longhorn_allow_encrypted_trim/tasks/process_volume.yml, justfile
This accomplishes what is documented by Longhorn on how to enable the trim command to work:
https://longhorn.io/docs/1.9.1/nodes-and-volumes/volumes/trim-filesystem/#encrypted-volumes
=> feat: include a new role to allow encrypted trim
