- images/kairos-ubuntu-22-lts/Earthfile
Will be generally nice to have
> Add zsh and usbutils to install list

- Earthfile
> Add shellcheck to lint

- .github/workflows/kairos-zsh-bundle.yml
- .github/workflows/usb-image.yml
- ansible/Earthfile
- ansible/roles/zsh/defaults/main.yml
- ansible/roles/zsh/tasks/main.yml
- ansible/roles/zsh/templates/zshrc
- images/Earthfile
- images/kairos-zsh-bundle/Earthfile
- images/kairos-zsh-bundle/run.sh
This is supposed to install the zsh configs defined by our Ansible role into /home/kairos
> Try to build a zsh bundle

- .github/workflows/kairos-zsh-bundle.yml
- images/kairos-zsh-bundle/Earthfile
This should help make it easier to test changes to images
> Push an image of the kairos-zsh-bundle on PR

- kustomization/components/kubevirt-operator/README.md
- kustomization/components/kubevirt-operator/kustomization.yml
- kustomization/components/kubevirt-operator/subscription.yml
Based off of https://github.com/sdwilsh/ansible-playbooks/blob/aa026b041b7e9ef09b5876cae275a026a2c557f9/kustomization/overlays/prod/olm-operators/subscriptions.yml
> Introduce the kubevirt component

- .github/workflows/kairos-ubuntu-22-lts.yml
- .github/workflows/kairos-zsh-bundle.yml
- .github/workflows/usb-image.yml
- .github/workflows/validate.yml
This should help with waiting on CI results if this pattern is successful
> Use Earthly satellites for faster CI builds

- devcontainer/features/src/ansible/devcontainer-feature.json
Would be great to have a lint that catches this.
> Bump dev container feature version

- devcontainer/features/src/ansible/devcontainer-feature.json
- devcontainer/features/src/ansible/install.sh
- devcontainer/features/src/ansible/updateContent.sh
Lifecycle hooks should let us access the contents of the repo that the feature is running in
> Run the playbook and ansible galaxy commands as part of the repo

- .devcontainer/devcontainer.json
This is something to start with. It will need some renovate annotations, probably an initial ansible play, and some other love.
> Add initial devcontainer definition

- devcontainer/features/src/ansible/install.sh
We need to setup sharing of GPG keys for this to work.
https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials#_sharing-gpg-keys
> Support GPG Signing of Commits

- .github/workflows/validate.yml
Likely an oversight from versioning the others. Did not dig into the history.
> Version the earthly version used in the validation flow

- ansible/Earthfile
- images/universal-silabs-flasher/Earthfile
This hopefully addresses the diff in #86
> Explicitly tag Python with docker versioning

- images/kairos-ubuntu-22-lts/Earthfile
> Fix kairos dep in image build script

- .devcontainer/devcontainer.json
- .vscode/extensions.json
- .vscode/settings.json
This allows us to more easily format things
> Tell vscode to use prettier to autoformat yaml and js

- .github/workflows/kairos-ubuntu-22-lts.yml
- .github/workflows/universal-silabs-flasher.yml
I forgot about the `TAG=` part in manual testing
> Fix version tagging on release

- Earthfile
- ansible/.config/ansible-lint.yml
This is setup to use the `min` profile for now, as we already pass that.
> Setup ansible-lint

- ansible/.config/ansible-lint.yml
- ansible/galaxy.yml
- ansible/meta/runtime.yml
- ansible/roles/minikube_test/handlers/main.yml
- ansible/roles/minikube_test/tasks/main.yml
- renovate.json
> Run ansible-lint at production

- .github/workflows/kairos-ubuntu-24-lts.yml
- images/kairos-ubuntu-24-lts/Dockerfile
- images/kairos-ubuntu-24-lts/Earthfile
This is in preperation for using the Kairos Factory to produce our image.
> Build a base image for Ubuntu 24.04

- .github/workflows/kairos-ubuntu-24-lts.yml
> Build correct image for kairos

- kustomization/components/factorio/kustomization.yml
- kustomization/components/factorio/service.yml
- kustomization/components/factorio/statefulset.yml
Taken from https://github.com/sdwilsh/ansible-playbooks/tree/main/kustomization/components/factorio
> Add factorio component

- kustomization/components/factorio/service.yml
The deployment is really two services in one: the admin service and game service. This lets us configure them separately.
> Split the factorio service

- .github/workflows/checks.yml
This will make many more jobs, but should complete faster, especially as we add more extensive testing for each component (and add more components!)
> feat: split kustomization tests into their own job

- kustomization/components/factorio/README.md
- kustomization/components/kube-vip/README.md
- kustomization/components/mosquitto/README.md
- kustomization/components/paperless/README.md
- kustomization/components/priorityclass/README.md
- kustomization/components/unifi-network-application/README.md
This change adds badges for all of our components to display the following information:
* Latest version, linking to the releases query for the component
* What Pod Security Standard it meets
* What Priority Class it uses
> docs: Add and Standardize Badging

- ansible/roles/minikube_test/defaults/main.yml
- renovate.json
Renovate did not know how to parse this.
Tested with https://regex101.com/r/FjGTz6/1
> fix: Make sure ansible test runner picks up k8s updates

- renovate/README.md
- renovate/recommended.json
This is what @robarnold and I both use, and this will allow us to have less config in our own projects.
> feat: Create a recommended renovate settings to share

- .github/workflows/image-vscode-ssh-server.yml
- .release-please-manifest.json
- images/vscode-ssh-server/Dockerfile
- images/vscode-ssh-server/README.md
- images/vscode-ssh-server/root/etc/ssh/sshd_config.d/overrides.conf
- images/vscode-ssh-server/root/init.sh
- release-please-config.json
Like the readme says, we can't use the linuxserver one. This is a pretty minimal one that I think will suffice.
> Initial version of the vscode ssh server

- .github/workflows/image-kairos-ubuntu.yml
- images/kairos-ubuntu/Dockerfile
This helps make sure update checks work correctly.
> fix: Specify the registory of our Kairos image

- images/vscode-ssh-server/README.md
Is this better? IDK. I need a change to test the release process
> fix: Update vscode readme link

- images/kairos-ubuntu/Dockerfile
- renovate.json
This also fixes renovate not being able to update automatically.
> feat: Upgrade to k3s 1.32.1+k3s1

- .devcontainer/devcontainer.json
We discussed in #381 that we don't know what this is needed for. Let's remove and re-add if/when it's needed.
> Remove Argo CD feature

- kustomization/components/unifi-network-application/configmap/generate-init-mongo.sh
Copypasta from https://github.com/linuxserver/docker-unifi-network-application/pull/149
> fix: Fix new installs of Unifi

- .github/workflows/release-please.yml
This will make everyone get spam, and not just everyone but me (so I get spam).  It will also be easier to setup email filters if desired.
> feat: Use Formwork Releaser GitHub app for Release Please

- renovate.json
I don't want to merge these PRs manually
> chore: schedule monthly samba digest updates
